### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by jasimi** [JosefJantzen/MMM-AlexaControl#48]
Hello
When I install the module and restart the Magicmirror I have a black screen with the mouse pointer. Where is the problem.

**Comment by JosefJantzen** [comment]
Hi, could you please post your config of the module and the log here? #48 was the same problem I think.

**Comment by jasimi** [comment]
I got it to work and there is no longer a black screen. I ran "npm install request" in the Alexa folder and it worked.
If I now search for devices in the Alexa APP, 6 new ones are found. But I can neither turn the monitor off or on nor change pages. It all went before the update.
What can I do there ?

**Comment by jasimi** [comment]
> magicmirror@2.17.1 start /home/pi/MagicMirror
> ./run-start.sh $1

[26.10.2021 18:34.04.438] [LOG]   Starting MagicMirror: v2.17.1
[26.10.2021 18:34.04.446] [LOG]   Loading config ...
[26.10.2021 18:34.04.455] [LOG]   Loading module helpers ...
[26.10.2021 18:34.04.458] [LOG]   No helper found for module: MMM-pages.
[26.10.2021 18:34.04.460] [LOG]   No helper found for module: alert.
[26.10.2021 18:34.04.482] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.04.483] [LOG]   Module helper loaded: updatenotification
[26.10.2021 18:34.04.484] [LOG]   No helper found for module: clock.
[26.10.2021 18:34.04.485] [LOG]   No helper found for module: clock2.
[26.10.2021 18:34.05.115] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.05.116] [LOG]   Module helper loaded: MMM-AlexaControl
[26.10.2021 18:34.05.397] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.05.398] [LOG]   Module helper loaded: calendar
[26.10.2021 18:34.05.400] [LOG]   No helper found for module: MMM-OpenmapWeather.
[26.10.2021 18:34.05.401] [LOG]   No helper found for module: weather.
[26.10.2021 18:34.05.402] [LOG]   No helper found for module: weatherforecast1.
[26.10.2021 18:34.06.096] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.06.097] [LOG]   Module helper loaded: MMM-Tado
[26.10.2021 18:34.06.757] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.06.760] [LOG]   Module helper loaded: MMM-DWD-WarnWeather
[26.10.2021 18:34.06.885] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.06.888] [LOG]   Module helper loaded: MMM-Fuel
[26.10.2021 18:34.07.508] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.07.511] [LOG]   Module helper loaded: MMM-SystemStats
[26.10.2021 18:34.07.516] [LOG]   No helper found for module: MMM-page-indicator.
[26.10.2021 18:34.07.519] [LOG]   No helper found for module: MMM-ioBroker.
[26.10.2021 18:34.07.525] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.07.526] [LOG]   Module helper loaded: MMM-MotionEye
[26.10.2021 18:34.07.568] [LOG]   Initializing new module helper ...
[26.10.2021 18:34.07.569] [LOG]   Module helper loaded: newsfeed
[26.10.2021 18:34.07.570] [LOG]   All module helpers loaded.
[26.10.2021 18:34.07.741] [LOG]   Starting server on port 8080 ... 
[26.10.2021 18:34.07.790] [LOG]   Server started ...
[26.10.2021 18:34.07.795] [LOG]   Connecting socket for: updatenotification
[26.10.2021 18:34.07.798] [LOG]   Connecting socket for: MMM-AlexaControl
[26.10.2021 18:34.07.799] [LOG]   MMM-AlexaControl helper, started...
[26.10.2021 18:34.07.801] [LOG]   Connecting socket for: calendar
[26.10.2021 18:34.07.802] [LOG]   Starting node helper for: calendar
[26.10.2021 18:34.07.804] [LOG]   Connecting socket for: MMM-Tado
[26.10.2021 18:34.07.805] [LOG]   Connecting socket for: MMM-DWD-WarnWeather
[26.10.2021 18:34.07.807] [LOG]   MMM-DWD-WarnWeather helper started...
[26.10.2021 18:34.07.814] [LOG]   Connecting socket for: MMM-Fuel
[26.10.2021 18:34.07.815] [LOG]   Starting module helper: MMM-Fuel
[26.10.2021 18:34.07.817] [LOG]   Connecting socket for: MMM-SystemStats
[26.10.2021 18:34.07.820] [LOG]   Connecting socket for: MMM-MotionEye
[26.10.2021 18:34.07.821] [LOG]   Starting module: MMM-MotionEye
[26.10.2021 18:34.07.822] [LOG]   Connecting socket for: newsfeed
[26.10.2021 18:34.07.823] [LOG]   Starting node helper for: newsfeed
[26.10.2021 18:34.07.825] [LOG]   Sockets connected & modules started ...
[26.10.2021 18:34.09.664] [LOG]   Launching application.
[26.10.2021 18:34.15.622] [LOG]   monitorToggle requested
[26.10.2021 18:34.15.699] [LOG]   server is listening on 10900
[26.10.2021 18:34.15.704] [LOG]   server is listening on 10901
[26.10.2021 18:34.15.708] [LOG]   server is listening on 10902
[26.10.2021 18:34.15.716] [LOG]   server is listening on 11000
[26.10.2021 18:34.15.723] [LOG]   server is listening on 11001
[26.10.2021 18:34.15.734] [LOG]   server is listening on 11002
[26.10.2021 18:34.15.740] [LOG]   server is listening on 11005
[26.10.2021 18:34.15.905] [LOG]   Create new calendarfetcher for url: <URL>
[26.10.2021 18:34.16.133] [LOG]       - MMM-Tado: Checking if all data is present
[26.10.2021 18:34.16.141] [LOG]       - MMM-Tado: Not all data present
[26.10.2021 18:34.16.689] [LOG]   Create new newsfetcher for url: https://www.welt.de/feeds/latest.rss - Interval: 300000
[26.10.2021 18:34.16.711] [INFO]  Checking git for module: default
[26.10.2021 18:34.16.803] [INFO]  Checking git for module: MMM-pages
[26.10.2021 18:34.16.890] [INFO]  Checking git for module: MMM-AlexaControl
[26.10.2021 18:34.16.981] [INFO]  Checking git for module: MMM-OpenmapWeather
[26.10.2021 18:34.17.089] [INFO]  Checking git for module: MMM-Tado
[26.10.2021 18:34.17.194] [INFO]  Checking git for module: MMM-DWD-WarnWeather
[26.10.2021 18:34.17.332] [INFO]  Checking git for module: MMM-Fuel
[26.10.2021 18:34.17.436] [INFO]  Checking git for module: MMM-SystemStats
[26.10.2021 18:34.17.510] [INFO]  Checking git for module: MMM-page-indicator
[26.10.2021 18:34.17.556] [INFO]  Checking git for module: MMM-MotionEye
[26.10.2021 18:34.17.917] [LOG]       - MMM-Tado: Checking if all data is present
[26.10.2021 18:34.17.919] [LOG]       - MMM-Tado: Not all data present
[26.10.2021 18:34.19.008] [LOG]       - MMM-Tado: Logged in
[26.10.2021 18:34.19.081] [LOG]       - MMM-Tado: Checking if all data is present
[26.10.2021 18:34.19.082] [LOG]       - MMM-Tado: Not all data present
[26.10.2021 18:34.37.291] [INFO]  Newsfeed-Fetcher: Broadcasting 30 items.
[26.10.2021 18:34.37.607] [LOG]       - MMM-Tado: Got me()
[26.10.2021 18:34.37.608] [LOG]       - MMM-Tado: Got homes()
[26.10.2021 18:34.37.995] [LOG]       - MMM-Tado: Checking if all data is present
[26.10.2021 18:34.37.997] [LOG]       - MMM-Tado: Not all data present
[26.10.2021 18:34.38.112] [LOG]       - MMM-Tado: Got zones()
[26.10.2021 18:34.42.189] [INFO]  Calendar-Fetcher: Broadcasting 10 events.
[26.10.2021 18:34.42.216] [LOG]       - MMM-Tado: Checking if all data is present
[26.10.2021 18:34.42.221] [LOG]       - MMM-Tado: Not all data present
[26.10.2021 18:34.43.235] [LOG]       - MMM-Tado: Checking if all data is present
[26.10.2021 18:34.43.237] [LOG]       - MMM-TADO: All data is present

**Comment by jasimi** [comment]
[26.10.2021 18:34.07.775] [WARN]  [33mYou're using a full whitelist configuration to allow for all IPs[39m
[26.10.2021 18:34.15.647] [ERROR] Whoops! There was an uncaught exception...
[26.10.2021 18:34.15.675] [ERROR] Error: bind EADDRINUSE 0.0.0.0:1900
    at dgram.js:337:20
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: -98,
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 1900
}
[26.10.2021 18:34.15.681] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[26.10.2021 18:34.15.687] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by jasimi** [comment]
},
                {
                        module: 'MMM-AlexaControl',
                        position: "top_bar",
                        config:{
                                pm2ProcessName: "mm",
				monitorToggle:"true",
                                vcgencmd: "vcgencmd",
				pages: "3",
				startPort:"11000",
				image: "false"
                                }
                },

**Comment by JosefJantzen** [comment]
I think the pages don't work because you defined the pages setting as String but it has to be int. So write the 3 without quotation marks.

**Comment by jasimi** [comment]
No that's not it. I removed the execution characters and it still doesn't work.
Before the update, I could switch the monitor on and off with Alexa and switch the 3 pages, now everything is found but nothing can be switched. 6 new devices were found in the Alexa app, but when I address one, the answer comes that the device cannot be reached. What shall I do.

**Comment by JosefJantzen** [comment]
Maybe it helps when you delete all devices in the Alexa app and discover them again. Also I saw in your [comment](https://github.com/JoChef2/MMM-AlexaControl/issues/48#issuecomment-952116585) that the port 1900 is used by something else on your pi. That causes also problems that are difficult or impossible to solve, look [here](https://github.com/JoChef2/MMM-AlexaControl/issues/35).

**Comment by jasimi** [comment]
I have now set the start port to 12000.
No improvement, I had previously deleted all devices in the Alexa APP, then searched and found them again, but they cannot be operated, they do not react.
But as I said, it had worked well for a long time.
![Screenshot_20211027-084943_Amazon Alexa](https://user-images.githubusercontent.com/61836987/139015718-c110e443-ef41-4818-9750-2b36c54f79f4.jpg)
.
